name: TestFlow

on:
  pull_request:
    branches: [ '*' ]

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  build:

    runs-on: ubuntu-latest
#   runs-on: self-hosted 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml
   
    # name: Configure AWS Credentials
    #  uses: aws-actions/configure-aws-credentials@v1
    #  if: ${{ always() }}
    #  with:
    #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #    aws-region: us-west-2
    
    # name: Checkout the CodeGuru Reviewer Action repository
    #  uses: actions/checkout@v2
    #  if: ${{ always() }}
    #  with:
    #    repository: vijejain/cicd-actions
    #    ref: refs/heads/main
    #    token: ${{ secrets.TOKEN }}   # Required for Private Beta
    #    path: ./.github/vijejain/cicd-actions

    # name: AWS CodeGuru Reviewer Scanner
    #  uses: ./.github/vijejain/cicd-actions
    #  if: ${{ always() }} 
    #  with:
    #    src_path: .         
    #    build_path: target 
    #    s3_bucket: 'codeguru-reviewer-test-cicd-bucket'  
    
    # name: Upload review result
    #  if: ${{ always() }}
    #  uses: github/codeql-action/upload-sarif@v1
    #  with:
    #    sarif_file: codeguru-results.sarif.json
